name: mini_shop_app
description: "A Mini-Shop App."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  badges: ^3.1.2
  dio: ^5.7.0
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff" # You can use a color or image for the background
  adaptive_icon_foreground: "assets/appicon.png" # For adaptive icons on Android

flutter:
  uses-material-design: true
  assets:
    - assets/
